@startuml
skinparam handwritten true
top to bottom direction

node "Client Browser" as Browser {
  [Razor Pages\n(HTML/CSS/JS)] as RazorPages
}

node "Service Métier" as WebServer {
  component "MagasinCentral.dll\n(Controllers & Views)" as Client
  component "MagasinCentral.Services.dll\n(Logique métier)" as Services
  component "MagasinCentral.Data.dll\n(EF Core & Models)" as DataLayer
}

node "PostgreSQL" as database {
  database "Base de données" as DB
}

Browser --> WebServer : HTTP/HTTPS
DataLayer --> database : TCP
@enduml
