name: CI/CD .NET Docker

on:
  push:
    branches: [main]

env:
  IMAGE_NAME: magasincentral
  DOCKERHUB_REPO: ${{ secrets.DOCKERHUB_USERNAME }}/magasincentral

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.tag.outputs.IMAGE_TAG }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install .NET 8.0 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Lint / Format check
        run: dotnet format --verify-no-changes
        continue-on-error: true

      - name: Run tests
        run: dotnet test --configuration Release --no-build --verbosity normal

      - name: Set Docker image tag
        id: tag
        run: echo "::set-output name=IMAGE_TAG::$(date +'%Y%m%d%H%M')"

  docker-build-and-push:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -f MagasinCentral/Dockerfile -t log430-lab2-MagasinCentral .

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Tag Docker image
        run: docker tag log430-lab2-MagasinCentral docker.io/${{ secrets.DOCKERHUB_USERNAME }}/log430-lab2-MagasinCentral:latest

      - name: Push Docker image
        run: docker push docker.io/${{ secrets.DOCKERHUB_USERNAME }}/log430-lab2-MagasinCentral:latest

  deploy:
    needs: docker-build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VM via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          password: ${{ secrets.VM_PASSWORD }}
          port: 22
          script: |
            cd ~/magasincentral
            docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_TOKEN }}"
            docker-compose pull
            docker-compose up -d --remove-orphans
